apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-bench-claim-premium
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Gi
  storageClassName: premium-rwo
