apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-bench-claim-standard
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Gi
  storageClassName: standard-rwo
